server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        #Nacos服务注册中心地址
        server-addr: my01:8848
    sentinel:
      transport:
        #配置Sentinel dashboard地址
        dashboard: my01:8080
        # Spring官网：sential的API默认8719端口，port将在应用程序的相应服务器上启动一个HTTP服务器，这个服务器将与Sentinel仪表板交互。
        #例如，如果在Sentinel仪表板中添加速率限制规则，则规则数据将被推到HTTP服务器并由HTTP服务器接收，然后HTTP服务器将该规则注册到Sentinel。
        port: 8719

# Actuator创建了所谓的endpoint来暴露HTTP或者JMX来监控和管理应用,暴露所有断点
management:
  endpoints:
    web:
      exposure:
        include: '*'




