server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        #自定义事务组名称需要与seata-server中的对应,service没有的直接填写default
        tx-service-group: my_test_tx_group

    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 862c3d87-b083-4888-babd-f0c64d68515f
        group: demoGroup


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_order?characterEncoding=utf8&connectTimeout=4000&socketTimeout=4000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1230123



# 取消hystrix服务降级，默认就是false
feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

# mybatis扫描mapper的路径
mybatis:
  mapperLocations: classpath:mapper/*.xml

# 与Nacos整合的Client端配置中心
seata:
  application-id: seata-order-service
  tx-service-group: my_test_tx_group

  service:
    vgroup-mapping:
      my_test_tx_group: default
  # 配置
  config:
    type: nacos
    nacos:
      server-addr: localhost:8848
      namespace: 862c3d87-b083-4888-babd-f0c64d68515f
      group: demoGroup
      username: nacos
      password: nacos
  # 注册
  registry:
    type: nacos
    nacos:
      server-addr: localhost:8848
      namespace: 862c3d87-b083-4888-babd-f0c64d68515f
      group: demoGroup
      username: nacos
      password: nacos
management:
  endpoints:
    web:
      exposure:
        include: "*"
