server:
  port: 83


spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: my01:8848


#消费者将要去访问的微服务名称(注册成功进nacos的微服务提供者),就不用在Controller写，但破坏了代码和配置文件分离的特性
service-url:
  nacos-user-service: http://nacos-payment-provider

